"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { AlertTriangle, ArrowUpRight, BarChart3, CircleCheck, RotateCcw, Zap } from "lucide-react";
import { useForm } from "react-hook-form";
import { simulateScenario, type InventoryItem } from "@/entities/inventory";
import { formatMoney, formatNumber } from "@/shared/lib";
import { Badge, Button, Card } from "@/shared/ui";
import { scenarioSchema, type ScenarioInput } from "../model/schema";

const defaults: ScenarioInput = { growthPercent: 8, budget: 20_000_000, serviceLevel: 95, delayDays: 0, injectAnomaly: false };

export function ScenarioPanel({ items, horizonDays }: { items: InventoryItem[]; horizonDays: number }) {
  const { register, watch, setValue, reset, formState: { errors } } = useForm<ScenarioInput>({ resolver: zodResolver(scenarioSchema), defaultValues: defaults, mode: "onChange" });
  const values = watch();
  const parsed = scenarioSchema.safeParse(values);
  const result = parsed.success ? simulateScenario(items, { ...parsed.data, horizonDays }) : null;

  return <div className="grid gap-5 xl:grid-cols-[320px_minmax(0,1fr)]"><Card className="p-5"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-blue-500">Параметры расчёта</p><h2 className="mt-2 text-lg font-bold">Что изменится, если…</h2><form className="mt-6 space-y-6" onSubmit={(event) => event.preventDefault()}><label className="block"><span className="flex justify-between text-xs font-semibold"><span>Целевой рост продаж</span><strong>+{values.growthPercent}%</strong></span><input type="range" min="0" max="50" step="1" {...register("growthPercent", { valueAsNumber: true })} className="mt-3 w-full accent-blue-500" />{errors.growthPercent && <span className="text-xs text-red-500">{errors.growthPercent.message}</span>}</label><label className="block"><span className="mb-2 block text-xs font-semibold">Лимит бюджета, ₸</span><input type="number" min="0" max="50000000" step="100000" {...register("budget", { valueAsNumber: true })} className="h-10 w-full rounded-xl border border-border bg-input px-3 text-sm outline-none focus:border-ring" />{errors.budget && <span className="text-xs text-red-500">{errors.budget.message}</span>}</label><label className="block"><span className="flex justify-between text-xs font-semibold"><span>Уровень сервиса</span><strong>{values.serviceLevel}%</strong></span><input type="range" min="90" max="99" step="1" {...register("serviceLevel", { valueAsNumber: true })} className="mt-3 w-full accent-violet-500" />{errors.serviceLevel && <span className="text-xs text-red-500">{errors.serviceLevel.message}</span>}</label><div className="space-y-2"><Button type="button" variant={values.delayDays === 14 ? "primary" : "secondary"} className="w-full justify-start" onClick={() => setValue("delayDays", values.delayDays === 14 ? 0 : 14, { shouldValidate: true })}><AlertTriangle className="h-4 w-4" />Задержка поставки +14 дней</Button><Button type="button" variant={values.injectAnomaly ? "primary" : "secondary"} className="w-full justify-start" onClick={() => setValue("injectAnomaly", !values.injectAnomaly, { shouldValidate: true })}><Zap className="h-4 w-4" />Вбросить оптовый заказ</Button></div><Button type="button" variant="ghost" onClick={() => reset(defaults)} className="w-full"><RotateCcw className="h-4 w-4" />Сбросить сценарий</Button></form></Card>
    <div className="space-y-5">{result ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-4"><p className="text-xs text-muted-foreground">Базовый план</p><strong className="mt-2 block text-lg">{formatMoney(result.baselineCost)}</strong></Card><Card className="p-4"><p className="text-xs text-muted-foreground">План сценария</p><strong className="mt-2 block text-lg text-blue-500">{formatMoney(result.scenarioCost)}</strong></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Укладывается в бюджет</p><strong className="mt-2 block text-lg text-emerald-500">{formatMoney(result.selectedCost)}</strong></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Риск дефицита</p><strong className="mt-2 block text-lg text-red-500">{result.riskCount} позиций</strong></Card></div><Card className="p-5"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-violet-500">Результат what-if</p><h2 className="mt-2 text-lg font-bold">Приоритет закупки</h2></div><BarChart3 className="h-5 w-5 text-muted-foreground" /></div><p className="mt-2 text-xs text-muted-foreground">При ограничении бюджета первыми остаются позиции с самым высоким риском дефицита и значимостью спроса. Исключено: {result.excludedCount}.</p><div className="mt-5 space-y-2">{result.rows.filter((row) => row.quantity > 0).map((row) => <div key={row.item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-border p-3 text-xs"><div><strong>{row.item.name}</strong><p className="mt-1 font-mono text-[10px] text-muted-foreground">{row.item.sku} · {formatNumber(row.quantity)} {row.item.unit}</p></div><div className="flex items-center gap-2"><strong>{formatMoney(row.cost)}</strong><Badge tone={row.included ? "green" : "red"}>{row.included ? "В ПЛАНЕ" : "ВНЕ БЮДЖЕТА"}</Badge></div></div>)}</div></Card>{values.injectAnomaly && <Card className="border-emerald-500/25 bg-emerald-500/5 p-5"><div className="flex items-center gap-2 text-emerald-500"><CircleCheck className="h-5 w-5" /><h3 className="font-bold">Защита прогноза сработала</h3></div><p className="mt-2 text-sm text-muted-foreground">Аномальная отгрузка 5 000 единиц не вошла в регулярную базу. Наивный расчёт увеличил бы план примерно на {formatMoney(result.anomalyNaiveExtra)} <ArrowUpRight className="inline h-3.5 w-3.5" />.</p></Card>}</> : <Card role="alert" className="p-5 text-sm text-red-500">Проверьте параметры сценария.</Card>}</div>
  </div>;
}
